# Generated by Django 5.2.6 on 2025-09-20 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="telegram_group_id",
            field=models.CharField(
                blank=True, default=None, max_length=50, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="base_app.group",
            ),
        ),
    ]
