# Generated by Django 5.2.6 on 2025-09-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0002_group_telegram_group_id_alter_student_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="is_active",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
