# Generated by Django 5.2.7 on 2025-10-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_topic_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_link',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
