# Generated by Django 5.2.7 on 2025-11-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_invitecode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('test', 'Test'), ('assignment', 'Maxsus topshiriq')], default='test', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('student', 'topic', 'task_type')},
        ),
    ]
