# Generated by Django 5.2.7 on 2025-11-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_alter_task_unique_together_task_task_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='test_answers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='test_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
