# Generated by Django 5.2.7 on 2025-11-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_task_test_answers_task_test_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='correct_answers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
