# Generated by Django 5.2.6 on 2025-11-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0008_topic_correct_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("milliy_sert", "Milliy sertifikat"),
                    ("attestatsiya", "Attestatsiya"),
                ],
                default="milliy_sert",
                help_text="Guruh qaysi kurs uchun",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="is_full",
            field=models.BooleanField(
                default=False, help_text="Guruh to'lganmi (50/50)"
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("milliy_sert", "Milliy sertifikat"),
                    ("attestatsiya", "Attestatsiya"),
                ],
                default="milliy_sert",
                help_text="Mavzu qaysi kurs uchun",
                max_length=20,
            ),
        ),
    ]
