# Generated by Django 5.2.6 on 2025-11-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0009_group_course_type_group_is_full_topic_course_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="is_full",
            field=models.BooleanField(
                default=True, help_text="Guruh to'lganmi (50/50)"
            ),
        ),
    ]
