# Generated by Django 5.2.7 on 2025-11-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_alter_group_is_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='course_type',
            field=models.CharField(choices=[('milliy_sert', 'Milliy Sertifikat'), ('attestatsiya', 'Attestatsiya')], default='milliy_sert', max_length=20),
        ),
    ]
