# Generated by Django 5.2.6 on 2025-12-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0011_task_course_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="is_full",
            field=models.BooleanField(
                default=True, help_text="Guruh to'lganmi (200/200)"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("milliy_sert", "Milliy Sertifikat"),
                    ("attestatsiya", "Attestatsiya"),
                ],
                default="attestatsiya",
                max_length=20,
            ),
        ),
    ]
