# Generated by Django 5.2.7 on 2025-11-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_task_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='is_full',
            field=models.BooleanField(default=False, help_text="Guruh to'lganmi (50/50)"),
        ),
    ]
