# Generated by Django 5.1.7 on 2026-01-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0012_alter_group_is_full_alter_task_course_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline dan keyin topshirilsa 80% ball beriladi",
                null=True,
            ),
        ),
    ]
