# Generated by Django 5.2.7 on 2025-12-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_alter_group_is_full'),
        ('base_app', '0012_alter_group_is_full_alter_task_course_type'),
    ]

    operations = [
    ]
