# Generated by Django 5.2.6 on 2026-01-04 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0013_topic_deadline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Kurs nomi (Milliy sertifikat, Attestatsiya, ...)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Kurs kodi (milliy_sert, attestatsiya, ...)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("test", "Test"), ("assignment", "Maxsus topshiriq")],
                        default="test",
                        help_text="Bu kursda qanday vazifa topshiriladi",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Kurs faolmi"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Kurs",
                "verbose_name_plural": "Kurslar",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="group",
            name="course_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("milliy_sert", "Milliy sertifikat"),
                    ("attestatsiya", "Attestatsiya"),
                ],
                help_text="DEPRECATED: Iltimos 'course' dan foydalaning",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="is_full",
            field=models.BooleanField(
                default=True, help_text="Guruh to'lganmi (50/50)"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="course_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("milliy_sert", "Milliy Sertifikat"),
                    ("attestatsiya", "Attestatsiya"),
                ],
                help_text="DEPRECATED: topic.course dan olinadi",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="grade",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Test uchun: to'g'ri javoblar soni (0-55). Vazifa uchun: admin bahosi (0-55)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="course_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("milliy_sert", "Milliy sertifikat"),
                    ("attestatsiya", "Attestatsiya"),
                ],
                help_text="DEPRECATED: Iltimos 'course' dan foydalaning",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Guruh qaysi kursga tegishli",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="groups",
                to="base_app.course",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Mavzu qaysi kursga tegishli",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="topics",
                to="base_app.course",
            ),
        ),
    ]
