# Generated by Django 5.2.7 on 2026-01-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_merge_20251217_2202'),
        ('base_app', '0013_topic_deadline'),
    ]

    operations = [
    ]
