# Generated by Django 5.1.7 on 2026-01-04 05:42

from django.db import migrations


def migrate_course_data(apps, schema_editor):
    """
    Eski course_type ma'lumotlarini yangi Course modeliga ko'chirish
    """
    Course = apps.get_model('base_app', 'Course')
    Group = apps.get_model('base_app', 'Group')
    Topic = apps.get_model('base_app', 'Topic')
    
    # 1. Kurslarni yaratish (agar mavjud bo'lmasa)
    milliy, _ = Course.objects.get_or_create(
        code='milliy_sert',
        defaults={
            'name': 'Milliy sertifikat',
            'task_type': 'assignment',  # Milliy sert - maxsus topshiriq
            'is_active': True
        }
    )
    
    attestatsiya, _ = Course.objects.get_or_create(
        code='attestatsiya',
        defaults={
            'name': 'Attestatsiya',
            'task_type': 'test',  # Attestatsiya - test
            'is_active': True
        }
    )
    
    # 2. Guruhlarni yangi Course ga bog'lash
    groups_milliy = Group.objects.filter(course_type='milliy_sert', course__isnull=True)
    groups_milliy.update(course=milliy)
    print(f"✅ {groups_milliy.count()} ta milliy_sert guruhi ko'chirildi")
    
    groups_attestatsiya = Group.objects.filter(course_type='attestatsiya', course__isnull=True)
    groups_attestatsiya.update(course=attestatsiya)
    print(f"✅ {groups_attestatsiya.count()} ta attestatsiya guruhi ko'chirildi")
    
    # 3. Topiclarni yangi Course ga bog'lash
    topics_milliy = Topic.objects.filter(course_type='milliy_sert', course__isnull=True)
    topics_milliy.update(course=milliy)
    print(f"✅ {topics_milliy.count()} ta milliy_sert topic ko'chirildi")
    
    topics_attestatsiya = Topic.objects.filter(course_type='attestatsiya', course__isnull=True)
    topics_attestatsiya.update(course=attestatsiya)
    print(f"✅ {topics_attestatsiya.count()} ta attestatsiya topic ko'chirildi")
    
    print("🎉 Ma'lumotlar muvaffaqiyatli ko'chirildi!")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - course dan course_type ga qaytarish
    """
    Group = apps.get_model('base_app', 'Group')
    Topic = apps.get_model('base_app', 'Topic')
    
    # Guruhlarni qaytarish
    for group in Group.objects.filter(course__isnull=False):
        group.course_type = group.course.code
        group.save()
    
    # Topiclarni qaytarish
    for topic in Topic.objects.filter(course__isnull=False):
        topic.course_type = topic.course.code
        topic.save()
    
    print("↩️ Ma'lumotlar eski holatga qaytarildi")


class Migration(migrations.Migration):
    dependencies = [
        (
            "base_app",
            "0014_course_alter_group_course_type_alter_group_is_full_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(migrate_course_data, reverse_migration),
    ]
