# Generated by Django 5.1.7 on 2026-01-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0015_migrate_to_course_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="admin_telegram_id",
            field=models.CharField(
                blank=True,
                help_text="Bu kurs uchun mas'ul admin Telegram ID",
                max_length=50,
                null=True,
            ),
        ),
    ]
