# Generated by Django 5.2.7 on 2026-01-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0014_merge_0013_merge_20251217_2202_0013_topic_deadline'),
        ('base_app', '0015_migrate_to_course_model'),
    ]

    operations = [
    ]
