# Generated by Django 5.2.7 on 2026-01-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0016_course_admin_telegram_id'),
        ('base_app', '0016_merge_20260104_1135'),
    ]

    operations = [
    ]
