# Generated by Django 5.2.7 on 2026-01-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0017_merge_20260104_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='course_type',
        ),
        migrations.AlterField(
            model_name='group',
            name='is_full',
            field=models.BooleanField(default=True, help_text="Guruh to'lganmi (50/50)"),
        ),
    ]
