# Generated by Django 5.2.7 on 2026-01-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0018_remove_group_course_type_remove_task_course_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course_type',
            field=models.CharField(blank=True, choices=[('milliy_sert', 'Milliy sertifikat'), ('attestatsiya', 'Attestatsiya')], help_text="DEPRECATED: Iltimos 'course' dan foydalaning", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='course_type',
            field=models.CharField(blank=True, choices=[('milliy_sert', 'Milliy Sertifikat'), ('attestatsiya', 'Attestatsiya')], help_text='DEPRECATED: topic.course dan olinadi', max_length=20, null=True),
        ),
    ]
