# Generated by Django 5.2.7 on 2026-01-21 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0019_group_course_type_task_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='course_type',
        ),
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text="Student qaysi guruhlarda o'qiydi (ko'p kurs)", related_name='enrolled_students', to='base_app.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, help_text="DEPRECATED: Iltimos 'groups' dan foydalaning (asosiy guruh)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='base_app.group'),
        ),
    ]
