# Generated by Django 5.2.7 on 2026-01-21 10:56

from django.db import migrations


def migrate_group_to_groups(apps, schema_editor):
    """Eski group fielddan yangi groups ManyToMany ga datalarni ko'chirish"""
    Student = apps.get_model('base_app', 'Student')
    
    for student in Student.objects.all():
        if student.group:
            # Eski group ni yangi groups ga qo'shamiz
            student.groups.add(student.group)
            print(f"✅ Migrated: {student.full_name} -> {student.group.name}")


def reverse_migration(apps, schema_editor):
    """Reverse: groups dan group ga qaytarish (rollback uchun)"""
    Student = apps.get_model('base_app', 'Student')
    
    for student in Student.objects.all():
        # Agar groups bo'sh bo'lmasa, birinchisini group ga qo'yamiz
        if student.groups.exists() and not student.group:
            first_group = student.groups.first()
            student.group = first_group
            student.save()
            print(f"✅ Reversed: {student.full_name} -> {first_group.name}")


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0020_add_student_groups'),
    ]

    operations = [
        migrations.RunPython(migrate_group_to_groups, reverse_migration),
    ]
