# Generated by Django 5.2.7 on 2026-02-06 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0022_topic_show_detailed_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
    ]
