# Generated by Django 5.2.7 on 2026-05-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0023_remove_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_students',
            field=models.PositiveIntegerField(default=30, help_text='Guruh maksimal talabalar soni'),
        ),
        migrations.AddField(
            model_name='group',
            name='score_max',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Bu guruhga kiradigan maksimal math_score (masalan: 22, 27, 35)', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='score_min',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Bu guruhga kiradigan minimal math_score (masalan: 1, 23, 28)', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='math_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='tuman',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='viloyat',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_full',
            field=models.BooleanField(default=False, help_text="Guruh to'lganmi (avtomatik hisoblanadi)"),
        ),
    ]
