# Generated by Django 5.2.7 on 2026-05-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0024_group_max_students_group_score_max_group_score_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='course_type',
        ),
    ]
