# Generated by Django 5.2.7 on 2026-05-16 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0026_coinwallet_cointransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
                'ordering': ['-marked_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('created_by', models.CharField(help_text='Admin telegram_id', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Sessiya tugash vaqti')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Davomat sessiyasi',
                'verbose_name_plural': 'Davomat sessiyalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='cointransaction',
            name='unique_wallet_topic_tasktype',
        ),
        migrations.RemoveConstraint(
            model_name='coinwallet',
            name='unique_student_course_wallet',
        ),
        migrations.AlterUniqueTogether(
            name='cointransaction',
            unique_together={('wallet', 'topic', 'task_type')},
        ),
        migrations.AlterUniqueTogether(
            name='coinwallet',
            unique_together={('student', 'course')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='base_app.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='base_app.attendancesession'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'session')},
        ),
    ]
