# Generated by Django 5.2.7 on 2026-06-24 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0032_paymentplan_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Operator profili',
                'verbose_name_plural': 'Operator profillari',
            },
        ),
        migrations.RemoveConstraint(
            model_name='paymentplan',
            name='unique_student_course_plan',
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Izoh (chegirma, maxsus narx va h.k.)'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentplan',
            unique_together={('student', 'course')},
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, related_name='operators', to='base_app.group', verbose_name='Biriktirilgan guruhlar'),
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
