# Generated by Django 5.2.7 on 2026-07-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0034_student_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_key', models.CharField(max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('weekdays', models.CharField(blank=True, default='', help_text="vergul bilan: mon,tue,wed,thu,fri,sat,sun. Bo'sh = har kuni", max_length=30)),
                ('hour', models.PositiveSmallIntegerField(default=21)),
                ('minute', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schedule sozlamasi',
                'verbose_name_plural': 'Schedule sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='WeeklyReportSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='last10', max_length=10)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Haftalik PDF sozlamasi',
                'verbose_name_plural': 'Haftalik PDF sozlamalari',
            },
        ),
    ]
