# Generated by Django 5.2.7 on 2026-07-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0036_seed_schedule_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_assignments',
            field=models.BooleanField(default=False, help_text="Bu kursda 'Maxsus topshiriq' (fayl/rasm) yuborish ham mumkinmi"),
        ),
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
