# Generated by Django 5.2.7 on 2026-07-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0037_course_has_assignments_task_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStreakSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oylik streak sozlamasi',
                'verbose_name_plural': 'Oylik streak sozlamalari',
                'unique_together': {('year', 'month')},
            },
        ),
    ]
