# Generated by Django 5.2.7 on 2026-07-19 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0038_monthly_streak_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='registration_strategy',
            field=models.CharField(choices=[('score_range', "Ball oralig'i bo'yicha"), ('capacity', "Sig'im bo'yicha ketma-ket"), ('role', "Rol bo'yicha (talaba/o'qituvchi)")], default='score_range', help_text="Ro'yxatdan o'tishda studentni qaysi guruhga biriktirish mantig'i", max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='target_role',
            field=models.CharField(blank=True, choices=[('student', 'Talaba'), ('teacher', "O'qituvchi")], help_text="Faqat kursning ro'yxatdan o'tish strategiyasi 'Rol bo'yicha' bo'lsa ishlatiladi", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registered_course',
            field=models.ForeignKey(blank=True, help_text="Student ro'yxatdan o'tishda tanlagan kurs (guruhga qayta biriktirishda ishlatiladi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_students', to='base_app.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Talaba'), ('teacher', "O'qituvchi")], help_text="Faqat 'Rol bo'yicha' strategiyali kursda ro'yxatdan o'tganda so'raladi", max_length=20, null=True),
        ),
    ]
